default:
  @just --list

prep-build:
  #!/usr/bin/env bash
  cp ../*.sql .

  for file in ../sql/*; do
    echo -e "\n\n-- $file\n$(cat $file)" >> create_schemamap_schema.sql
    echo "" >> create_schemamap_schema.sql
  done

build: prep-build
  docker build . -t schemamap/postgres:latest -t schemamap/postgres:16.2

# One-time setup of BuildKit so multi-arch builds are possible
buildx-setup:
 docker buildx create --name mybuilder --use
 docker buildx install

# Builds all common architectures that are supported by the official Postgres image
buildx-and-push: prep-build
  docker build --platform linux/amd64,linux/arm64,linux/arm/v7 . -t schemamap/postgres:latest -t schemamap/postgres:16.2 --push

login:
  docker login -u schemamap

push:
  docker push schemamap/postgres:16.2
  docker push schemamap/postgres:latest

up: prep-build
  docker-compose up --build

psql:
  PGPASSWORD=schemamap psql -h 127.0.0.1 -p 5433 -U schemamap postgres

clean:
  docker-compose rm -f
