default:
  @just --list

build:
  cargo build

# integrations tests whole CLI interface, assumes process-compose is running
test:
  #!/usr/bin/env bash
  set -eo pipefail

  cargo test # fail-fast if unit tests fail

  cargo build

  export PATH="$PATH:./target/debug"

  pgclear

  # Simulating CI/hands-free use-case
  export DATABASE_URL="postgresql://$(whoami)@localhost:5432/schemamap_test"

  echo "Initializing with $DATABASE_URL"
  schemamap init --input=false --conn="$DATABASE_URL"
  echo "Reinitializing to test idempotency"
  schemamap init --input=false #--conn="$DATABASE_URL"

  echo "Running schemamap doctor"
  schemamap doctor
