default:
  @just --list

up:
  docker-compose up -d

down:
  docker-compose down

psql:
  docker exec -it odoo-mydb-1 psql -U odoo odoo_test

docker-ps:
  docker ps

sleep-5:
  # waiting 5 seconds for roles to be created
  sleep 5

schemamap-init:
  # odoo puts the test DB under $DBNAME_test, in our case odoo_test
  # the rest of the connection params are inferred from the docker-compose.yml file
  schemamap init --dbname odoo_test

schemamap-doctor:
  schemamap doctor

test: up docker-ps sleep-5 schemamap-init schemamap-doctor
