name: Create release & SQL assets on tag push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create create_schemamap_schema.sql
      run: |
        for file in sql/*; do
          echo -e "\n\n-- $file\n$(cat $file)" >> create_schemamap_schema.sql
          echo "" >> create_schemamap_schema.sql
        done

    - name: Upload Release assets
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          create_schemamap_users.sql
          create_schemamap_schema.sql
          grant_schemamap_usage.sql
          install_schemamap.sh
