name: Create release & SQL assets on tag push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload Release assets
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          rust/create_schemamap_users.sql
          rust/create_schemamap_schema.sql
          rust/grant_schemamap_usage.sql
          install_schemamap.sh
