name: "Build & Test"

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: nixbuild/nix-quick-install-action@v26
      with:
        nix_conf: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          keep-outputs = true

    # https://github.com/nix-community/cache-nix-action#usage
    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v4
      with:
        key: cache-${{ matrix.os }}-${{ hashFiles('devenv.*') }}
        restore-keys: |
          cache-${{ matrix.os }}-

        gc-linux: true
        gc-max-store-size-linux: 1000000000

        purge-caches: true
        purge-key: cache-${{ matrix.os }}-
        purge-created: true
        purge-created-max-age: 42

    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install tarball+https://github.com/cachix/devenv/tarball/v0.6.3

    - name: Run pre-commit hooks, verify formats
      run: devenv ci

    - name: Run tests
      run: devenv shell ci-test
